# Generated by Django 4.2.21 on 2025-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_youtubeshort_contact_phone_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='events/'),
            preserve_default=False,
        ),
    ]
