# Generated by Django 4.2.21 on 2025-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='services/'),
            preserve_default=False,
        ),
    ]
