# Generated by Django 4.2.21 on 2025-05-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_event_image_alter_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
