# Generated by Django 4.2.21 on 2025-05-13 20:51

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=13, validators=[web.models.validate_phone]),
            preserve_default=False,
        ),
    ]
