# Generated by Django 4.2.21 on 2025-05-14 09:29

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_direction_event_date_project_link_vacancy_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/', validators=[web.models.validate_file]),
        ),
    ]
