# Generated by Django 4.2.21 on 2025-05-14 09:57

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_contact_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[web.models.validate_phone]),
        ),
    ]
