# Generated by Django 4.2.21 on 2025-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_teammember_about_about_content_event_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Фото мероприятия', 'verbose_name_plural': 'Фото мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='toolimage',
            options={'verbose_name': 'Фото инструментов', 'verbose_name_plural': 'Фото инструментов'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Инструменты', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='youtubeshort',
            options={'verbose_name': 'Ютуб-Шортс', 'verbose_name_plural': 'Ютуб-Шортсы'},
        ),
    ]
