# Generated by Django 4.2.21 on 2025-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
