# Generated by Django 4.2.21 on 2025-05-20 10:12

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='contacts/vacancy/', validators=[web.models.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка вакансии',
                'verbose_name_plural': 'Заявки вакансий',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='youtubeshort',
            name='content',
        ),
        migrations.RemoveField(
            model_name='youtubeshort',
            name='title',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
